ZAI_API_KEY = "sk-5cf8b28515feae220acbf1dda3487a71aca2552a96806076"
RESUME_URL = "https://docs.google.com/document/d/1y8qge7gB9otoVnTxj88ZPyYRaVfxsyFNBWF3tITcaPk/edit?tab=t.0"
MODEL_NAME = "glm-4.7-flash"

[service_account_json]
type = "service_account"
project_id = "resume-agent-476008"
private_key_id = "3b9e98286acedb3ec7f322ddfc50f95bfaed08c2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDJNYEu4ZIq08iF
TTZbiAnViUOo9Lp6HuCeLg1iAqk8pxviu8L3fO6RAjyngPYLl67GNJocVOhsxl4t
Uh2iuhvhDxOqo+mBaErQijAucl6TpI1sZWguJ5hjlsWb2AWAoV+GiQ5etsM1YdnL
5Vwo9rhFw/dSgU3i4N1vVt1+Z3ROlj+Rk/O6jApGcXGQjITvPswq1KDTrBUAcDeS
SK2kA3aBRAKdMVSEogoB+JUTLqX7ejGFIsN7sRlDbRmR3voHv/si8ePPLaix99HM
9e1+XK61YVVYk5yWTnmwaH/PBi8NKDsLu0XwGgAwbGnzqS5Uep3EIzXgAOPeUAA5
6qUYOSONAgMBAAECggEAEQ6JF06l/nLE9+VAwLz6ixs/chjfn1nzaVVhaw1AstST
vO0f160ZPY+2pph8bc/Q+sUbdLVknVFU9dCVPzs5q82EZEh66K53pnq1yj+FxvcB
yiOak6G6/bjv+DMgMZ78eGzb8VQwSNvfrl+Q0s7Uy40+RRnoXrL4nTym5X/4UG+u
MURAkI8p03YPlKRwqZh1jqUcDXCnjbV97Sy22vBy+gFkhhexJ1TkM5+q+OcUETtF
H/8VPQJfa468h5C1kSReVwoiZPJmr3sb4heBHtwNKGa5eRUFXZGhR/gxzzLZgp+i
y9BepCrEprmTQJ1S4KZJkPN2ApI0PydlcHHJrRZ6PQKBgQD8mrlCplV6fTkwEhVX
LSMReP9shdW3vDFjeFhL0vfCM3+Im/EOig/HfrmaJV//IAAF97yElb4Pqp/HgFSL
EV7RVU8+uJ92eLqsNnS2nyPKBRMmWE9smVwmwnaLfKzAnh6/aENQMAkcgkG5i9Hc
kt3V7al1oEtQNjxr5kLSBpHQQwKBgQDL6eqQ6Lodc02G7vluJPkZ+zye pQRh25UX
CfNkJuCESKardMLpW9eZgGkVmQjlqgjAykp+ylHhENyNqmOwsYJ4u7gsrgLuclsM
/N/lpgPLRzw0BGf0dRsMpYhxh/hq6PCwPXj7wwrQuBgS/aILbO1FVLNGWlVHp9jg
x4DWBhSn7wKBgQDl698cr1G2gCyBeLQ7+TWmPcAgA2GYL4+0vmGAArLI7R70NRyg
40Ghj9NYXxSVn4bl56yL8dBhaiis6j4JpvHrD/9lU56xswoWnip13zwwMZZQnKkO
bDjYfsBwDjcfy8yo5DoAzvg8HsO8I2wNnRCWHBDWo+RpSjSM8bV4fcpTCQKBgQCW
MrGNlW7pnHGhj0r435EAmzc2n9QPhJ9XvgOiZKSBq8Xgivu6yeSP867zsqqECG+0
Gg0vQTV4c2QRkU0m7ElvRs5NUstj+aWpdmYxEMzAobLtmcU8ojmPYiqTfZT0oqoP
FuiTgUHpJYDOFDaU9eH7bH00t/sS8cZlI255tzblzwKBgQDlEH0DC9WjHTStAu99
77sF51bFuRkPomj73ccip/IwU7SyE0/+e6bm5G3UESiYFi9QPFnZS81n2Qd4ISZb
6A3JuzurFIeWwWN/K0wXVMIu8XnB397u2RzgLvB76VDksieUTgxuYtDoOh5ELhHz
hgrGiHm18EcDTo4X9XIgnR+wpQ==
-----END PRIVATE KEY-----
"""
client_email = "resume-agent@resume-agent-476008.iam.gserviceaccount.com"
client_id = "116953473376442473957"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/resume-agent%40resume-agent-476008.iam.gserviceaccount.com"
universe_domain = "googleapis.com"